---
apiVersion: v1
kind: Service
metadata:
  name: mysql-server
spec:
  selector:
    app: mysql
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        imagePullPolicy: IfNotPresent
        args:
          - --character-set-server=utf8
          - --innodb_log_buffer_size=32M
          - --innodb_log_file_size=80M
          - --max_allowed_packet=8M  
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql.user
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql.password
        - name: MYSQL_DATABASE
          valueFrom: 
              configMapKeyRef:
                name: databaseconfig
                key: mysql.database
        resources:
          limits:
            memory: 512Mi
        ports:
        - containerPort: 3306