---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: lac
    service: lac-svc
  name: lac-svc
  annotations:
    description: The LAC Service
spec:
  selector:
    app: lac
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: container-lac-ssg-port
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 32080
      name: container-lac-http-port
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laclocdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laclocrepo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lac-dc
  labels:
    app: lac
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: lac
    spec:
      containers:
      - name: lac-container
        image: caliveapicreator/5.1.00
        imagePullPolicy: Always
        ports:
          - containerPort: 8081
          - containerPort: 8080
        env:
          - name: TZ
            value: "EDT"
          - name: ca_accept_license
            value: "enu"
          - name: LAC_ADMIN_MAX_CONN
            value: "100"
        resources:
          requests:
              cpu: 1000m
              memory: 2Gi
          limits:
              cpu: 2000m
              memory: 3Gi
        volumeMounts:
          - name: lac-db-persistent-storage
            mountPath: /usr/local/CALiveAPICreator/databases
          - name: lac-repo-persistent-storage
            mountPath: /home/tomcat/CALiveAPICreator.repository
      volumes:
        - name: lac-db-persistent-storage
          persistentVolumeClaim:
            claimName: laclocdb
        - name: lac-repo-persistent-storage
          persistentVolumeClaim:
            claimName: laclocrepo